name: 'macOS v1.2.0'

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Nim installation
        id: nim-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            ~/.choosenim
            bin/nim
            bin/nimsuggest
            bin/nimpretty
            bin/testament
            bin/nimgrep
            bin/nim_dbg
            bin/nimble
            bin/atlas
          key: nim-${{ runner.os }}-2.2.0

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          nimble install -y nimcrypto
          rm -rf dist/*
          mkdir -p dist
          mkdir -p dist/lib

      - name: Compile and package
        run: |
          nim c -d:macos -d:strip -d:release --out:jwlFusion-arm64 src/jwlFusion.nim
          nim c -d:macos -d:strip -d:release -l:'-target x86_64-apple-macosx10.13' -t:'-target x86_64-apple-macosx10.13' --out:jwlFusion-x86_64 src/jwlFusion.nim
          lipo -create -output dist/jwlFusion jwlFusion-x86_64 jwlFusion-arm64
          cp lib/libjwlCore.dylib dist/libjwlCore.dylib
          chmod +x dist/jwlFusion
          xattr -c dist/jwlFusion
          chmod +x dist/libjwlCore.dylib
          xattr -c dist/libjwlCore.dylib
          tar -czvf dist/jwlFusion_macos.tar.gz -C dist jwlFusion libjwlCore.dylib

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_macos.tar.gz
          path: dist/jwlFusion_macos.tar.gz