name: 'Build Windows binary v1.0.0'

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  windows:
    name: Build Windows binary
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          nimble install -y --depsOnly

      - name: Compile
        run: |
          mkdir -p dist
          nim c -d:release -d:version=${{ inputs.TAG }} src/jwlFusion.nim
          mv src/jwlFusion.exe dist/jwlFusion.exe

      - name: Copy DLLs to dist
        run: |
          cp lib/jwlCore.dll dist/
          cp lib/sqlite3_64.dll dist/

      - name: Test binary
        run: |
          cd dist
          ./jwlFusion.exe --help

      - name: Create ZIP archive with proper structure
        run: |
          Compress-Archive -Path dist/* -DestinationPath dist/jwlFusion-windows.zip

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion-windows.zip
          path: dist/jwlFusion-windows.zip