name: 'macOS v1.0.2'

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  macos:
    name: Build macOS binary
    runs-on: macos-14
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Nim installation
        id: nim-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
            ~/.choosenim
            bin/nim
            bin/nimsuggest
            bin/nimpretty
            bin/testament
            bin/nimgrep
            bin/nim_dbg
            bin/nimble
            bin/atlas
          key: nim-${{ runner.os }}-2.2.0

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          nimble install -y --depsOnly

      - name: Clear dist directory
        run: |
          rm -rf dist/*
          mkdir -p dist
          mkdir -p dist/lib

      - name: Compile for ${{ matrix.architecture }}
        run: |
          nim c -d:strip -d:release --passL:-Wl,-rpath,@executable_path/lib --out:dist/jwlFusion src/jwlFusion.nim

      - name: Copy shared library to dist/lib
        run: |
          cp lib/libjwlCore_${{ matrix.architecture }}.dylib dist/lib/libjwlCore.dylib

      - name: Fix shared library path in binary
        run: |
          install_name_tool -change lib/libjwlCore.dylib @executable_path/lib/libjwlCore.dylib dist/jwlFusion

      - name: Create .tar.gz archive for ${{ matrix.architecture }}
        run: |
          tar -czvf dist/jwlFusion_macos_${{ matrix.architecture }}.tar.gz -C dist jwlFusion lib/libjwlCore.dylib

      - name: Upload binary for ${{ matrix.architecture }}
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_macos_${{ matrix.architecture }}.tar.gz
          path: dist/jwlFusion_macos_${{ matrix.architecture }}.tar.gz