name: 'Linux and Windows v1.0.2'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  build:
    name: Build for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies and compiler
        run: |
          nimble install -y --depsOnly
          sudo snap install zig --classic --beta
          nimble install zigcc

      - name: Clear dist directory
        run: |
          rm -rf dist/*
          mkdir -p dist
          mkdir -p dist/lib

      - name: Compile and package
        run: |
          nim c -d:linux -d:strip -d:release --out:dist/jwlFusion src/jwlFusion.nim
          cp lib/libjwlCore-x86_64.so dist/lib/libjwlCore.so
          tar -czvf dist/jwlFusion_linux_x86_64.tgz -C dist jwlFusion lib/libjwlCore.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_linux_x86_64.tgz
          path: dist/jwlFusion_linux_x86_64.tgz

      - name: Clear dist directory
        run: |
          rm -rf dist/*
          mkdir -p dist
          mkdir -p dist/lib

      - name: Compile and package
        run: |
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target aarch64-linux-gnu" --passl:"-target aarch64-linux-gnu" --forceBuild:on --os:linux --cpu:aarch64 -d:linux -d:strip -d:release --out:dist/jwlFusion src/jwlFusion.nim
          cp lib/libjwlCore-aarch64.so dist/lib/libjwlCore.so
          tar -czvf dist/jwlFusion_linux_aarch64.tgz -C dist jwlFusion lib/libjwlCore.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_linux_aarch64.tgz
          path: dist/jwlFusion_linux_aarch64.tgz

      - name: Clear dist directory
        run: |
          rm -rf dist/*
          mkdir -p dist

      - name: Compile and package
        run: |
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target x86_64-windows" --passl:"-target x86_64-windows" --forceBuild:on --os:windows -d:windows -d:strip -d:release --out:dist/jwlFusion.exe src/jwlFusion.nim
          cp lib/jwlCore.dll dist/
          zip -j dist/jwlFusion_windows_amd64.zip dist/jwlFusion.exe dist/jwlCore.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_windows_amd64.zip
          path: dist/jwlFusion_windows_amd64.zip