name: 'Linux and Windows v1.0.2'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  linux:
    name: Build for Linux and Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies and compiler
        run: |
          nimble install -y --depsOnly
          sudo snap install zig --classic --beta
          nimble install zigcc

      - name: Compile
        run: |
          mkdir -p dist
          nim c -d:linux -d:amd64 -d:strip -d:release --out:dist/jwlFusion_linux_x86_64 src/jwlFusion.nim
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target aarch64-linux-gnu" --passl:"-target aarch64-linux-gnu" --forceBuild:on --os:linux --cpu:arm64 -d:linux -d:arm64 -d:strip -d:release --out:dist/jwlFusion_linux_arm64 src/jwlFusion.nim
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target x86_64-windows" --passl:"-target x86_64-windows" --forceBuild:on --os:windows -d:windows -d:amd64 -d:strip -d:release --out:dist/jwlFusion_amd64.exe src/jwlFusion.nim

      - name: Copy shared libraries to dist/lib
        run: |
          mkdir -p dist/lib
          cp lib/libjwlCore*.so dist/lib/
          cp lib/jwlCore.dll dist/lib/

      - name: Create archives
        run: |
          tar -czvf dist/jwlFusion_linux_arm64.tgz -C dist jwlFusion_linux_arm64 lib/libjwlCore-arm64.so
          tar -czvf dist/jwlFusion_linux_x86_64.tgz -C dist jwlFusion_linux_x86_64 lib/libjwlCore-x86_64.so
          zip -j dist/jwlFusion_windows_amd64.zip dist/jwlFusion.exe dist/lib/jwlCore.dll

      - name: Upload jwlFusion_linux_arm64.tgz
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_linux_arm64.tgz
          path: dist/jwlFusion_linux_arm64.tgz
      - name: Upload jwlFusion_linux_x86_64.tgz
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_linux_x86_64.tgz
          path: dist/jwlFusion_linux_x86_64.tgz
      - name: Upload jwlFusion_windows_amd64.zip
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion_windows_amd64.zip
          path: dist/jwlFusion_windows_amd64.zip