name: 'Build Linux binary v1.0.1'

on:
  workflow_call:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  linux:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          nimble install -y --depsOnly
          sudo apt install zig
          nimble install zigcc

      - name: Compile
        run: |
          mkdir -p dist
          nim c -d:linux -d:amd64 -d:strip -d:release --out:dist/jwlFusion_linux_x86_64 src/jwlFusion.nim
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target aarch64-linux-gnu" --passl:"-target aarch64-linux-gnu" --forceBuild:on --os:linux --cpu:arm64 -d:linux -d:arm64 -d:strip -d:release --out:dist/jwlFusion_linux_arm64 src/jwlFusion.nim
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target x86_64-windows" --passl:"-target x86_64-windows" --forceBuild:on --os:windows -d:windows -d:amd64 -d:strip -d:release --out:dist/jwlFusion_amd64.exe src/jwlFusion.nim
          nim c --cc:clang --clang.exe="zigcc" --clang.linkerexe="zigcc" --passc:"-target aarch64-windows-gnu" --passl:"-target aarch64-windows-gnu" --forceBuild:on --os:windows -d:windows -d:arm64 -d:strip -d:release --out:dist/jwlFusion_arm64.exe src/jwlFusion.nim

      - name: Copy shared library to dist/lib
        run: |
          mkdir -p dist/lib
          cp lib/libjwlCore*.so dist/lib/

      - name: Test binary
        run: |
          dist/jwlFusion_linux_x86_64 --help

      - name: Create .tgz archive with proper structure
        run: |
          tar -czvf dist/jwlFusion-linux.tgz -C dist jwlFusion_* lib/libjwlCore*.so

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: jwlFusion-linux.tgz
          path: dist/jwlFusion-linux.tgz