name: 'Test Release v1.0.0'

on:
  workflow_dispatch:
    inputs:
      TAG:
        default: 'testing'
        required: true
        type: string

jobs:
  release:
    name: Create release draft
    runs-on: ubuntu-latest
    outputs:
      changelog-section: ${{ steps.extract.outputs.changelog_section }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract section from changelog
        id: extract
        env:
          CHANGELOG_FILE: "CHANGELOG.md"
        run: |
          if [[ ! -f "$CHANGELOG_FILE" ]]; then
            echo "Error: File '$CHANGELOG_FILE' not found!"
            exit 1
          fi
          changelog_section=$(awk '
          /^## / { h2_count++ } 
          h2_count == 2 && !/^## / && !/^$/ { in_section = 1 } 
          h2_count == 3 { in_section = 0 } 
          in_section { 
              if (/^[[:space:]]*$/) { 
                  empty_buffer = empty_buffer $0 "\n" 
              } else { 
                  printf "%s", empty_buffer 
                  empty_buffer = "" 
                  print 
              } 
          }
          ' "$CHANGELOG_FILE")
          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog_section" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Use the extracted section
        run: |
          echo "Extracted section:"
          echo "${{ steps.extract.outputs.changelog_section }}"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.TAG }}
          name: ${{ inputs.TAG }}
          draft: true
          body: |
            ${{ steps.extract.outputs.changelog_section }}
            ____
            This is a test
